#!/usr/bin/env bash
#  Bash script that displays the visitor IP along with the HTTP status code from the Apache log file.

while IFS=: read -r f1 f2 f3 f4 f5 f6 f7; do
awk "The user $f1 is part of the $f4 gang, lives in $f6 and rides $f7. $f3's place is protected by the passcode $f2, more info about the user here: $f5"
done < "/etc/passwd"
