#!/usr/bin/env bash

# A script that displays "Best School" 10 times.

# A script that displays Best School and then "Hi" on a new line.
 
count =o

while [ $count -lt 10 ]
do
   if [ $count -eq 9 ]
   then
       echo "Hi"
   fi
   echo "Best School"
   (( count++ ))
done
