#!/usr/bin/env bash
# This script displays numbers form 1 to 20 and some bad lucks.

count=1

while [ $count -le 20 ]
do
    echo "$count"
    case $count in
           "4") echo "bad luch from China";;
           "9") echo "bad luck from Japan";;
           "17") echo " bad lucl from Italy";;
    esac
     (( count++ ))
done
