#!/usr/bin/env bash
# This script prints the information about school

if [ -e "school" ]
then
     echo "school file exists"
     if [ -s "school" ] 
     then 
	   echo "file is not empty" 
     else
           echo "file is empty"
     fi

     if [ -f "school" ]	
     then
 	     echo "school is regular file"
     fi
else
     echo "school file does not exist"
fi

