#!/usr/bin/env bash
# This script that stops 4-to_infinity_and_beyond

# get the pid of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# terminate the infinate process
if [ -n "$id" ]
then
 kill -15 "$id"
fi 
